[default.extend-words]
Hashi = "Hashi"
HashiCorp = "HashiCorp"
MyApp = "MyApp"
OpenAPIv3 = "OpenAPIv3"
AKS = "AKS"
IST = "IST"

[files]
extend-exclude = [
  "docs/assets/*",
  "docs/legacy/*",
  "scripts/ignore_this.sh",
  "venv/*",
  ".env.local",
  ".gitignore",
  "mkdocs.yml",
  "requirements.txt",
  "**/.*"
]